branches:
  only:
    - master

matrix:
  include:
    - name: Dataset

      language:
        python

      python:
        - 3.7.4

      services:
        - postgresql

      before_install:
        - wget https://dl.google.com/go/go1.12.12.linux-amd64.tar.gz
        - sudo tar -xvf go1.12.12.linux-amd64.tar.gz
        - sudo mv go /usr/local
        - export GOROOT=/usr/local/go
        - export GOPATH=$HOME/Projects/Proj1
        - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        - go version
        - go get -u gopkg.in/src-d/go-siva.v1/...
        - go get github.com/src-d/datasets/PublicGitArchive/pga
        - go get -v github.com/src-d/datasets/PublicGitArchive/pga-create/...

      install:
        - pip install requests

      script:
        - pga --help
        - siva version
        - pga-create --help
